name: powersync

services:
  warp:
    image: caomingjun/warp
    container_name: warp
    restart: always
    networks:
      - powersync_network
    # add removed rule back (https://github.com/opencontainers/runc/pull/3468)
    device_cgroup_rules:
      - 'c 10:200 rwm'
    ports:
      - '1080:1080'
    environment:
      - WARP_SLEEP=2
      # - WARP_LICENSE_KEY= # optional
      # - WARP_ENABLE_NAT=1 # enable nat
    cap_add:
      # Docker already have them, these are for podman users
      - MKNOD
      - AUDIT_WRITE
      # additional required cap for warp, both for podman and docker
      - NET_ADMIN
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
      - net.ipv4.conf.all.src_valid_mark=1
      # Enable IPv6 forwarding
      - net.ipv4.ip_forward=1
      - net.ipv6.conf.all.forwarding=1
      - net.ipv6.conf.all.accept_ra=2
    volumes:
      - ./data:/var/lib/cloudflare-warp
    healthcheck:
      test:
        [
          'CMD',
          'curl',
          '--socks5-hostname',
          '127.0.0.1:1080',
          'https://cloudflare.com/cdn-cgi/trace'
        ]
      interval: 5s
      timeout: 1s
      retries: 15

  mongo:
    image: mongo:7.0
    command: --replSet rs0 --bind_ip_all --quiet
    restart: unless-stopped
    networks:
      - powersync_network
    ports:
      - 27017:27017
    volumes:
      - mongo_storage:/data/db
    depends_on:
      warp:
        condition: service_healthy

  # Initializes the MongoDB replica set. This service will not usually be actively running
  mongo-rs-init:
    image: mongo:7.0
    networks:
      - powersync_network
    depends_on:
      mongo:
        condition: service_started
      warp:
        condition: service_healthy
    restart: on-failure
    entrypoint:
      - bash
      - -c
      - 'mongosh --host mongo:27017 --eval ''try{rs.status().ok && quit(0)} catch {} rs.initiate({_id: "rs0", version: 1, members: [{ _id: 0, host : "mongo:27017" }]})'''

  powersync:
    restart: unless-stopped
    image: journeyapps/powersync-service:latest
    command: ['start', '-r', 'unified']
    networks:
      - powersync_network
    environment:
      POWERSYNC_CONFIG_PATH: /config/powersync-actions.yml
      NODE_OPTIONS: --max-old-space-size=1000
      PS_SUPABASE_JWT_SECRET: ${PS_SUPABASE_JWT_SECRET}
      PS_DATA_SOURCE_URI: ${PS_DATA_SOURCE_URI}
      PS_MONGO_URI: mongodb://mongo:27017/powersync_demo
      PS_PORT: ${PS_PORT}
    develop:
      watch:
        - action: sync+restart
          path: ./config
          target: /config
    healthcheck:
      test:
        [
          'CMD',
          'node',
          '-e',
          "fetch('http://localhost:${PS_PORT}/probes/liveness').then(r => r.ok ? process.exit(0) : process.exit(1)).catch(() => process.exit(1))"
        ]
      interval: 5s
      timeout: 1s
      retries: 15
    ports:
      - ${PS_PORT}:${PS_PORT}
    depends_on:
      mongo-rs-init:
        condition: service_completed_successfully
      warp:
        condition: service_healthy
    volumes:
      - ./config:/config

  # demo-client:
  #   build:
  #     dockerfile: demo-client.dockerfile
  #     args:
  #       VITE_SUPABASE_URL: ${EXPO_PUBLIC_SUPABASE_URL}
  #       VITE_SUPABASE_ANON_KEY: ${EXPO_PUBLIC_SUPABASE_ANON_KEY}
  #       VITE_POWERSYNC_URL: ${EXPO_PUBLIC_POWERSYNC_URL}
  #   ports:
  #     - 4170:4173

networks:
  powersync_network:
    enable_ipv6: true
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.20.0.0/16
        - subnet: fd00::/80

volumes:
  mongo_storage:
