name: 'Setup and install'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/package-lock.json'
        node-version-file: '.nvmrc'
        cache: 'npm'

    - shell: bash
      run: npm install
