name: 'Setup and install + Expo'
description: 'Common setup steps for Actions'

inputs:
  EXPO_TOKEN:
    description: 'You must provide an EXPO_TOKEN secret linked to this projects Expo account in this repos secrets. Learn more: https://docs.expo.dev/eas-update/github-actions'
    required: true

runs:
  using: composite
  steps:
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/package-lock.json'
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ inputs.EXPO_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: npm install
