name: 'Setup and install + Expo'
description: 'Common setup steps for Actions'

runs:
  using: composite
  steps:
    - name: Check for EXPO_TOKEN
      shell: bash
      run: |
        if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
          echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
          exit 1
        fi

    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        cache-dependency-path: '**/package-lock.json'
        node-version-file: '.nvmrc'
        cache: 'npm'

    - name: Setup EAS
      uses: expo/expo-github-action@v8
      with:
        eas-version: latest
        token: ${{ secrets.EXPO_TOKEN }}

    - name: Install dependencies
      shell: bash
      run: npm install
