import type { ConfigPlugin } from '@expo/config-plugins';
import {
  AndroidConfig,
  withAndroidManifest,
  withGradleProperties,
  withPodfileProperties
} from '@expo/config-plugins';
import { ConfigContext, ExpoConfig } from 'expo/config';

// The Gradle daemon runs out of Metaspace with the default 512m cap on this
// project, killing builds partway through. android/gradle.properties is
// regenerated by `expo prebuild --clean`, so the bump must live here.
const withGradleMemory: ConfigPlugin = (config) =>
  withGradleProperties(config, (c) => {
    c.modResults = c.modResults.map((item) =>
      item.type === 'property' && item.key === 'org.gradle.jvmargs'
        ? { ...item, value: '-Xmx4096m -XX:MaxMetaspaceSize=1536m' }
        : item
    );
    return c;
  });

const projectId = 'fafd03a9-a42c-44c7-849c-b0f84fbffe93';
const iconDark = './assets/icons/icon_dark.png';
const iconLight = './assets/icons/icon_light.png';
// const iconMono = './assets/icons/icon_mono.png';

const siteHost = 'langquest.org';
const uniqueIdentifier = 'com.etengenesis.langquest';

const appVariant =
  process.env.EXPO_PUBLIC_APP_VARIANT ||
  (process.env.NODE_ENV === 'development' ? 'development' : 'production');

function getAppName(variant: string) {
  switch (variant) {
    case 'development':
      return 'LangQuest (Dev)';
    case 'preview':
      return 'LangQuest (Preview)';
    default:
      return 'LangQuest';
  }
}

function getBundleIdentifier(variant: string) {
  switch (variant) {
    case 'development':
      return `${uniqueIdentifier}.development`;
    case 'preview':
      return `${uniqueIdentifier}.preview`;
    default:
      return uniqueIdentifier;
  }
}

function getScheme(variant: string) {
  switch (variant) {
    case 'development':
      return 'langquest-dev';
    case 'preview':
      return 'langquest-preview';
    default:
      return 'langquest';
  }
}

function getSiteHosts(variant: string): string[] {
  switch (variant) {
    case 'development':
      return [siteHost, `preview.${siteHost}`];
    case 'preview':
      return [`preview.${siteHost}`];
    default:
      return [siteHost];
  }
}

// Alternate app-icon set, declared at build time. Alias names are generic
// (ThemeA01..ThemeB05) and images live under generic folders, so the intent is
// not discoverable from filenames or config. The home-screen labels come from
// the encoded manifest below (kept in sync with features/appearance/profiles.data.ts;
// decoded here at prebuild time so plaintext labels never sit in tracked source,
// and land only in the generated, git-ignored native project). The decode is
// inlined because the Expo config loader cannot resolve local TS imports.
const APPEARANCE_KEY = 'aP8qZ3Lm';
const APPEARANCE_MANIFEST =
  'OisaGD4Rdk8AYAlTdhEtAQgxSz87XilPW3JsGT9eKSxRYRpdeFUtAAg8QVNgEQ1PTXJUEDhWIE9bcnsQNlA5AQAkVwN4TmAWQzlcU2ARLV1TchRTO18lDBIeWRw/EXZPNThdHD9yfF9DfBoXO14lARhyAlMbEWBPDTFaFDYRdk8iMVQSL18tGQ4iGgx2SG4EBXICUzsDf09NclkdM1I/IwA9XVNgERgFBD1dMGoAbkFDNlkcM181T1tyeVN2ESAMAzVUU2ARDwwNM00dO0cjH0MtFAp4WihPW3JZQW4RYE8APFEQKX0tAARyAlMOWykABBEIRXgfbgsAPVEdIxF2TyByFFM2Ui4IDXICUxlSIA4UPFkFNUFuEE0rGhg+EXZPAGANU3YRLQEIMUs/O14pT1tybBk/XiksUWUaXXhVLQAIPEFTYBENT01yVBA4ViBPW3J7EDZQOQEAJFcDeE5gFkM5XFNgES5dUHIUUztfJQwSHlkcPxF2TzU4XRw/cXxcQ3waFzteJQEYcgJTGBFgTw0xWhQ2EXZPLz9MFCkRMUEaclEVeAluD1FiGl14UiAEACN2EDdWbldDBFAUN1YOXVNyFFM8UiEEDSkaS3hxbkFDPFkTP19uV0MeVwU/QG4QTSsaGD4Rdk8DYAtTdhEtAQgxSz87XilPW3JsGT9eKS9RYxpdeFUtAAg8QVNgEQ5PTXJUEDhWIE9bcnYeLlY/Txx8Q1MzV25XQzIIRXgfbgwNOVkCFFIhCENqGiUyViEII2AMU3YRKgwMOVQIeAluL0N8Gh07USkBQ2oaPzVHKR5DLRQKeFooT1tyWkFvEWBPADxRECl9LQAEcgJTDlspAAQSCER4H24LAD1RHSMRdk8jchRTNlIuCA1yAlMUXDgIEnJFLA==';

function decodeAppearanceLabels(): {
  aliasName: string;
  label: string;
  id: string;
}[] {
  const bytes = Buffer.from(APPEARANCE_MANIFEST, 'base64');
  let out = '';
  for (let i = 0; i < bytes.length; i++) {
    out += String.fromCharCode(
      (bytes[i] ?? 0) ^ APPEARANCE_KEY.charCodeAt(i % APPEARANCE_KEY.length)
    );
  }
  return JSON.parse(out) as { aliasName: string; label: string; id: string }[];
}

function getAppearanceIcons() {
  return decodeAppearanceLabels().map((profile) => {
    const dir = `./assets/appearance/${profile.id}`;
    return {
      name: profile.aliasName,
      ios: `${dir}/icon.png`,
      android: {
        foregroundImage: `${dir}/adaptive-icon.png`,
        backgroundColor: '#ffffff'
      }
    };
  });
}

// expo-alternate-app-icons generates one <activity-alias> per icon
// (".MainActivity<Name>") but only gives it the LAUNCHER filter plus the
// config-declared intent filters. Two fixes are layered on top:
//   1. android:label — each disguise needs its own home-screen name.
//   2. deep-link parity — while a disguise is active, .MainActivity is
//      DISABLED, so any VIEW filter living only there stops resolving.
//      That includes the app scheme (langquest-preview://) and the dev-client
//      scheme (exp+langquest://) the CLI uses to reopen the app. Copying all
//      of MainActivity's VIEW filters onto every alias keeps links working
//      whichever component is enabled.
// Manifest mods execute in reverse plugin order, so this plugin is listed
// BEFORE expo-alternate-app-icons in `plugins` to run after it.
const withAppearanceLabels: ConfigPlugin = (config) =>
  withAndroidManifest(config, (c) => {
    const mainApplication = AndroidConfig.Manifest.getMainApplicationOrThrow(
      c.modResults
    );
    const mainActivity = AndroidConfig.Manifest.getMainActivityOrThrow(
      c.modResults
    );
    const labels = new Map(
      decodeAppearanceLabels().map((p) => [
        `.MainActivity${p.aliasName}`,
        p.label
      ])
    );

    type ManifestElement = { $: Record<string, string> };
    type IntentFilter = {
      action?: ManifestElement[];
      [key: string]: unknown;
    };
    const isViewFilter = (f: IntentFilter) =>
      (f.action ?? []).some(
        (a) => a.$['android:name'] === 'android.intent.action.VIEW'
      );

    const mainViewFilters = (
      (mainActivity['intent-filter'] ?? []) as unknown as IntentFilter[]
    ).filter(isViewFilter);

    // The manifest types don't model <activity-alias>, but the XML parser
    // exposes it like any other element.
    const aliases = ((
      mainApplication as unknown as Record<string, unknown>
    )['activity-alias'] ?? []) as (ManifestElement & {
      'intent-filter'?: IntentFilter[];
    })[];
    for (const alias of aliases) {
      const label = labels.get(alias.$['android:name'] ?? '');
      if (!label) continue;
      alias.$['android:label'] = label;
      const launcherFilters = (alias['intent-filter'] ?? []).filter(
        (f) => !isViewFilter(f)
      );
      alias['intent-filter'] = [...launcherFilters, ...mainViewFilters];
    }
    return c;
  });

export default ({ config }: ConfigContext): ExpoConfig =>
  withUseThirdPartySQLitePod({
    ...config,
    owner: 'eten-genesis',
    name: getAppName(appVariant),
    slug: 'langquest',
    version: '2.2.3',
    orientation: 'portrait',
    icon: iconLight,
    scheme: getScheme(appVariant),
    userInterfaceStyle: 'automatic',
    buildCacheProvider: 'eas',
    ios: {
      icon: {
        light: iconLight,
        dark: iconDark
        // tinted: iconMono
      },
      supportsTablet: true,
      requireFullScreen: true,
      bundleIdentifier: getBundleIdentifier(appVariant),
      associatedDomains: getSiteHosts(appVariant).map((h) => `applinks:${h}`),
      config: {
        usesNonExemptEncryption: false
      },
      infoPlist: {
        NSMicrophoneUsageDescription:
          'LangQuest needs access to your microphone to record voice translations.'
      }
    },
    android: {
      adaptiveIcon: {
        foregroundImage: './assets/icons/adaptive-icon.png',
        monochromeImage: './assets/icons/adaptive-icon-mono.png',
        backgroundColor: '#ffffff'
      },
      package: getBundleIdentifier(appVariant),
      intentFilters: [
        {
          action: 'VIEW',
          autoVerify: true,
          data: [
            ...getSiteHosts(appVariant).flatMap((host) => [
              {
                scheme: 'https',
                host,
                pathPattern: '/.*/reset-password'
              },
              {
                scheme: 'https',
                host,
                pathPattern: '/.*/registration-confirmation'
              },
              {
                scheme: 'https',
                host,
                pathPattern: '/.*/notifications'
              }
            ]),
            ...getSiteHosts(appVariant).map((host) => ({
              scheme: getScheme(appVariant),
              host
            }))
          ],
          category: ['BROWSABLE', 'DEFAULT']
        }
      ]
    },
    web: {
      bundler: 'metro',
      favicon: iconLight
    },
    plugins: [
      'expo-build-properties',
      'expo-font',
      'expo-router',
      // TODO: migrate existing localization to expo-localization
      'expo-localization',
      'expo-asset',
      ['expo-audio', { enableBackgroundPlayback: false }],
      'expo-image',
      [
        'expo-build-properties',
        {
          ios: {
            deploymentTarget: '15.5'
          }
        }
      ],
      [
        'expo-splash-screen',
        {
          image: iconLight,
          backgroundColor: '#f5f5ff',
          dark: {
            image: iconDark,
            backgroundColor: '#131320'
          },
          imageWidth: 150
        }
      ],
      'expo-dev-client',
      'expo-sharing',
      'expo-sqlite',
      'expo-secure-store',
      withAppearanceLabels,
      ['expo-alternate-app-icons', getAppearanceIcons()],
      ['testflight-dev-deploy', { enabled: appVariant === 'development' }],
      'posthog-react-native/expo',
      withGradleMemory
    ],
    experiments: {
      typedRoutes: true,
      reactCompiler: true
    },
    extra: {
      supabaseUrl: process.env.EXPO_PUBLIC_SUPABASE_URL,
      supabaseAnonKey: process.env.EXPO_PUBLIC_SUPABASE_ANON_KEY,
      powersyncUrl: process.env.EXPO_PUBLIC_POWERSYNC_URL,
      eas: {
        projectId
      }
    },
    updates: {
      url: `https://u.expo.dev/${projectId}`
    },
    runtimeVersion: {
      policy: 'appVersion'
    }
  } as ExpoConfig);

const withUseThirdPartySQLitePod: ConfigPlugin = (expoConfig) => {
  return withPodfileProperties(expoConfig, (config) => {
    config.modResults = {
      ...config.modResults,
      'expo.updates.useThirdPartySQLitePod': 'true'
    };
    return config;
  });
};
