// AUTO-GENERATED FILE. DO NOT EDIT.
// Generated by scripts/generate-local-tables.ts
// Creates _local table variants for offline sync

import { relations, sql } from 'drizzle-orm';
import { int, sqliteView, text } from 'drizzle-orm/sqlite-core';
import {
  createAssetContentLinkTable,
  createAssetTable,
  createAssetTagLinkTable,
  createBlockedContentTable,
  createBlockedUsersTable,
  createInviteTable,
  createLanguageTable,
  createNotificationTable,
  createProfileProjectLinkTable,
  createProfileTable,
  createProjectClosureTable,
  createProjectLanguageLinkTable,
  createProjectTable,
  createQuestAssetLinkTable,
  createQuestClosureTable,
  createQuestTable,
  createQuestTagLinkTable,
  createReportsTable,
  createRequestTable,
  createSubscriptionTable,
  createTagTable,
  createVoteTable
} from './drizzleSchemaColumns';

// NOTE: If you are using Drizzle with PowerSync and need to refer to the Postgres type for sync rules,
// see the official PowerSync documentation for the correct column types:
// https://docs.powersync.com/usage/sync-rules/types#types

// columns moved to ./drizzleSchemaColumns

export const profile_local = createProfileTable('local');

export const user_localRelations = relations(
  profile_local,
  ({ many, one }) => ({
    created_languages: many(language_local, { relationName: 'creator' }),
    ui_language: one(language_local, {
      fields: [profile_local.ui_language_id],
      references: [language_local.id],
      relationName: 'uiLanguage'
    }),
    sent_invites: many(invite_local, { relationName: 'invite_sender' }),
    received_invites: many(invite_local, { relationName: 'invite_receiver' }),
    sent_requests: many(request_local, { relationName: 'request_sender' })
  })
);

export const language_local = createLanguageTable('local', {
  profile: profile_local
});

export const language_localRelations = relations(
  language_local,
  ({ one, many }) => ({
    creator: one(profile_local, {
      fields: [language_local.creator_id],
      references: [profile_local.id],
      relationName: 'creator'
    }),
    uiUsers: many(profile_local, { relationName: 'uiLanguage' }),
    sourceLanguageProjects: many(project_local, {
      relationName: 'sourceLanguage'
    }),
    targetLanguageProjects: many(project_local, {
      relationName: 'targetLanguage'
    })
  })
);

export const project_local = createProjectTable('local', {
  language: language_local,
  profile: profile_local
});

export const project_localRelations = relations(
  project_local,
  ({ one, many }) => ({
    target_language: one(language_local, {
      fields: [project_local.target_language_id],
      references: [language_local.id],
      relationName: 'targetLanguage'
    }),
    quests: many(quest_local),
    profile_project_links: many(profile_project_link_local),
    source_languages: many(project_language_link_local),
    invites: many(invite_local),
    requests: many(request_local)
  })
);

// (removed duplicate early definition of project_language_link)
export const quest_local = createQuestTable('local', {
  project: project_local,
  profile: profile_local
});

export const quest_localRelations = relations(quest_local, ({ one, many }) => ({
  project: one(project_local, {
    fields: [quest_local.project_id],
    references: [project_local.id]
  }),
  parent: one(quest_local, {
    fields: [quest_local.parent_id],
    references: [quest_local.id],
    relationName: 'quest_parent'
  }),
  children: many(quest_local, { relationName: 'quest_parent' }),
  tags: many(quest_tag_link_local),
  assets: many(quest_asset_link_local)
}));

export const tag_local = createTagTable('local');

export const tag_localRelations = relations(tag_local, ({ many }) => ({
  quests: many(quest_tag_link_local),
  assets: many(asset_tag_link_local)
}));

export const quest_tag_link_local = createQuestTagLinkTable('local', {
  quest: quest_local,
  tag: tag_local
});

export const quest_tag_link_localRelations = relations(
  quest_tag_link_local,
  ({ one }) => ({
    quest: one(quest_local, {
      fields: [quest_tag_link_local.quest_id],
      references: [quest_local.id]
    }),
    tag: one(tag_local, {
      fields: [quest_tag_link_local.tag_id],
      references: [tag_local.id]
    })
  })
);

export const asset_local = createAssetTable(
  'local',
  {
    language: language_local,
    project: project_local,
    profile: profile_local
  },
  {
    order_index: int().notNull().default(0)
  }
);

export const asset_localRelations = relations(asset_local, ({ one, many }) => ({
  source_language: one(language_local, {
    fields: [asset_local.source_language_id],
    references: [language_local.id]
  }),
  project: one(project_local, {
    fields: [asset_local.project_id],
    references: [project_local.id]
  }),
  source_asset: one(asset_local, {
    fields: [asset_local.source_asset_id],
    references: [asset_local.id],
    relationName: 'asset_source'
  }),
  children: many(asset_local, { relationName: 'asset_parent' }),
  tags: many(asset_tag_link_local),
  quests: many(quest_asset_link_local),
  content: many(asset_content_link_local),
  votes: many(vote_local)
}));

export const asset_tag_link_local = createAssetTagLinkTable('local', {
  asset: asset_local,
  tag: tag_local
});

export const asset_tag_link_localRelations = relations(
  asset_tag_link_local,
  ({ one }) => ({
    asset: one(asset_local, {
      fields: [asset_tag_link_local.asset_id],
      references: [asset_local.id]
    }),
    tag: one(tag_local, {
      fields: [asset_tag_link_local.tag_id],
      references: [tag_local.id]
    })
  })
);

export const quest_asset_link_local = createQuestAssetLinkTable('local', {
  quest: quest_local,
  asset: asset_local
});

export const quest_asset_link_localRelations = relations(
  quest_asset_link_local,
  ({ one }) => ({
    quest: one(quest_local, {
      fields: [quest_asset_link_local.quest_id],
      references: [quest_local.id]
    }),
    asset: one(asset_local, {
      fields: [quest_asset_link_local.asset_id],
      references: [asset_local.id]
    })
  })
);

// Project-language link with explicit type separation (source/target)
export const project_language_link_local = createProjectLanguageLinkTable(
  'local',
  {
    project: project_local,
    language: language_local
  }
);

export const project_language_link_localRelations = relations(
  project_language_link_local,
  ({ one }) => ({
    project: one(project_local, {
      fields: [project_language_link_local.project_id],
      references: [project_local.id]
    }),
    language: one(language_local, {
      fields: [project_language_link_local.language_id],
      references: [language_local.id]
    })
  })
);

export const reports_local = createReportsTable('local', {
  profile: profile_local
});

export const blocked_users_local = createBlockedUsersTable('local', {
  profile: profile_local
});

export const blocked_users_localRelations = relations(
  blocked_users_local,
  ({ one }) => ({
    blocker: one(profile_local, {
      fields: [blocked_users_local.blocker_id],
      references: [profile_local.id],
      relationName: 'blocker'
    }),
    blocked: one(profile_local, {
      fields: [blocked_users_local.blocked_id],
      references: [profile_local.id],
      relationName: 'blocked'
    })
  })
);

export const blocked_content_local = createBlockedContentTable('local', {
  profile: profile_local
});

export const blocked_content_localRelations = relations(
  blocked_content_local,
  ({ one }) => ({
    profile: one(profile_local, {
      fields: [blocked_content_local.profile_id],
      references: [profile_local.id]
    })
  })
);

export const report_localRelations = relations(reports_local, ({ one }) => ({
  reporter: one(profile_local, {
    fields: [reports_local.reporter_id],
    references: [profile_local.id]
  }),
  translation: one(asset_local, {
    fields: [reports_local.record_id],
    references: [asset_local.id],
    relationName: 'asset_reports'
  })
}));

export const vote_local = createVoteTable('local', {
  asset: asset_local,
  profile: profile_local
});

export const vote_localRelations = relations(vote_local, ({ one }) => ({
  asset: one(asset_local, {
    fields: [vote_local.asset_id],
    references: [asset_local.id]
  }),
  creator: one(profile_local, {
    fields: [vote_local.creator_id],
    references: [profile_local.id]
  })
}));

export const asset_content_link_local = createAssetContentLinkTable('local', {
  asset: asset_local,
  language: language_local
});

export const asset_content_link_localRelations = relations(
  asset_content_link_local,
  ({ one }) => ({
    asset: one(asset_local, {
      fields: [asset_content_link_local.asset_id],
      references: [asset_local.id]
    }),
    source_language: one(language_local, {
      fields: [asset_content_link_local.source_language_id],
      references: [language_local.id]
    })
  })
);

export const invite_local = createInviteTable('local', {
  senderProfile: profile_local,
  receiverProfile: profile_local,
  project: project_local
});

export const invite_localRelations = relations(invite_local, ({ one }) => ({
  sender: one(profile_local, {
    fields: [invite_local.sender_profile_id],
    references: [profile_local.id],
    relationName: 'invite_sender'
  }),
  receiver: one(profile_local, {
    fields: [invite_local.receiver_profile_id],
    references: [profile_local.id],
    relationName: 'invite_receiver'
  }),
  project: one(project_local, {
    fields: [invite_local.project_id],
    references: [project_local.id]
  })
}));

export const request_local = createRequestTable('local', {
  senderProfile: profile_local,
  project: project_local
});

export const request_localRelations = relations(request_local, ({ one }) => ({
  sender: one(profile_local, {
    fields: [request_local.sender_profile_id],
    references: [profile_local.id],
    relationName: 'request_sender'
  }),
  project: one(project_local, {
    fields: [request_local.project_id],
    references: [project_local.id]
  })
}));

export const notification_local = createNotificationTable('local', {
  profile: profile_local
});

export const notification_localRelations = relations(
  notification_local,
  ({ one }) => ({
    profile: one(profile_local, {
      fields: [notification_local.profile_id],
      references: [profile_local.id]
    })
  })
);

export const profile_project_link_local = createProfileProjectLinkTable(
  'local',
  {
    profile: profile_local,
    project: project_local
  }
);

export const profileProjectLink_localRelations = relations(
  profile_project_link_local,
  ({ one }) => ({
    profile: one(profile_local, {
      fields: [profile_project_link_local.profile_id],
      references: [profile_local.id]
    }),
    project: one(project_local, {
      fields: [profile_project_link_local.project_id],
      references: [project_local.id]
    })
  })
);

export const subscription_local = createSubscriptionTable('local', {
  profile: profile_local
});

export const subscription_localRelations = relations(
  subscription_local,
  ({ one }) => ({
    profile: one(profile_local, {
      fields: [subscription_local.profile_id],
      references: [profile_local.id]
    })
  })
);

// ====================================
// VIEWS
// ====================================

// Asset tag categories view - extracts distinct tag categories (part before ':') for each quest via asset tags
export const asset_tag_categories_local = sqliteView('asset_tag_categories', {
  quest_id: text('quest_id').notNull(),
  tag_categories: text('tag_categories', { mode: 'json' }).$type<string[]>() // SQLite stores as comma-separated string
}).as(sql`
  SELECT
    q.id AS quest_id,
    GROUP_CONCAT(DISTINCT t.key) AS tag_categories
  FROM quest_local q
  JOIN quest_asset_link_local qal ON q.id = qal.quest_id
  JOIN asset_local a ON qal.asset_id = a.id
  JOIN asset_tag_link_local atl ON a.id = atl.asset_id
  JOIN tag_local t ON atl.tag_id = t.id
  GROUP BY q.id
  ORDER BY q.id
`);

// Quest tag categories view - extracts distinct tag categories for all quests in each project
export const quest_tag_categories_local = sqliteView('quest_tag_categories', {
  project_id: text('project_id').notNull(),
  tag_categories: text('tag_categories', { mode: 'json' }).$type<string[]>() // SQLite stores as comma-separated string
}).as(sql`
  SELECT
    p.id AS project_id,
    GROUP_CONCAT(DISTINCT t.key) AS tag_categories
  FROM project_local p
  JOIN quest_local q ON q.project_id = p.id
  JOIN quest_asset_link_local qal ON q.id = qal.quest_id
  JOIN asset_local a ON qal.asset_id = a.id
  JOIN asset_tag_link_local atl ON a.id = atl.asset_id
  JOIN tag_local t ON atl.tag_id = t.id
  GROUP BY p.id
  ORDER BY p.id
`);

// ====================================
// CLOSURE AND AGGREGATE TABLES
// ====================================

export const quest_closure_local = createQuestClosureTable('local', {
  quest: quest_local,
  project: project_local
});

export const quest_closure_localRelations = relations(
  quest_closure_local,
  ({ one }) => ({
    quest: one(quest_local, {
      fields: [quest_closure_local.quest_id],
      references: [quest_local.id]
    }),
    project: one(project_local, {
      fields: [quest_closure_local.project_id],
      references: [project_local.id]
    })
  })
);

export const project_closure_local = createProjectClosureTable('local', {
  project: project_local
});

export const project_closure_localRelations = relations(
  project_closure_local,
  ({ one }) => ({
    project: one(project_local, {
      fields: [project_closure_local.project_id],
      references: [project_local.id]
    })
  })
);

// Deprecated - remove after migration
export const quest_aggregates_local = quest_closure_local;
