// Import SVG components
import type { ImageSourcePropType } from 'react-native';

// Book SVG icons mapping
import { BIBLE_BOOKS } from '../constants/bibleStructure';

/* eslint-disable @typescript-eslint/no-require-imports, @typescript-eslint/no-unsafe-assignment */
export const BOOK_ICON_MAP: Record<string, ImageSourcePropType> = {
  gen: require('../assets/book-icons/gen.webp'),
  exo: require('../assets/book-icons/exo.webp'),
  lev: require('../assets/book-icons/lev.webp'),
  num: require('../assets/book-icons/num.webp'),
  deu: require('../assets/book-icons/deu.webp'),
  jos: require('../assets/book-icons/jos.webp'),
  jdg: require('../assets/book-icons/jdg.webp'),
  rut: require('../assets/book-icons/rut.webp'),
  '1sa': require('../assets/book-icons/1sa.webp'),
  '2sa': require('../assets/book-icons/2sa.webp'),
  '1ki': require('../assets/book-icons/1ki.webp'),
  '2ki': require('../assets/book-icons/2ki.webp'),
  '1ch': require('../assets/book-icons/1ch.webp'),
  '2ch': require('../assets/book-icons/2ch.webp'),
  ezr: require('../assets/book-icons/ezr.webp'),
  neh: require('../assets/book-icons/neh.webp'),
  est: require('../assets/book-icons/est.webp'),
  job: require('../assets/book-icons/job.webp'),
  psa: require('../assets/book-icons/psa.webp'),
  pro: require('../assets/book-icons/pro.webp'),
  ecc: require('../assets/book-icons/ecc.webp'),
  sng: require('../assets/book-icons/sng.webp'),
  isa: require('../assets/book-icons/isa.webp'),
  jer: require('../assets/book-icons/jer.webp'),
  lam: require('../assets/book-icons/lam.webp'),
  ezk: require('../assets/book-icons/ezk.webp'),
  dan: require('../assets/book-icons/dan.webp'),
  hos: require('../assets/book-icons/hos.webp'),
  joe: require('../assets/book-icons/jol.webp'),
  amo: require('../assets/book-icons/amo.webp'),
  oba: require('../assets/book-icons/oba.webp'),
  jon: require('../assets/book-icons/jon.webp'),
  mic: require('../assets/book-icons/mic.webp'),
  nah: require('../assets/book-icons/nam.webp'),
  hab: require('../assets/book-icons/hab.webp'),
  zep: require('../assets/book-icons/zep.webp'),
  hag: require('../assets/book-icons/hag.webp'),
  zec: require('../assets/book-icons/zec.webp'),
  mal: require('../assets/book-icons/mal.webp'),
  mat: require('../assets/book-icons/mat.webp'),
  mar: require('../assets/book-icons/mrk.webp'),
  luk: require('../assets/book-icons/luk.webp'),
  joh: require('../assets/book-icons/jhn.webp'),
  act: require('../assets/book-icons/act.webp'),
  rom: require('../assets/book-icons/rom.webp'),
  '1co': require('../assets/book-icons/1co.webp'),
  '2co': require('../assets/book-icons/2co.webp'),
  gal: require('../assets/book-icons/gal.webp'),
  eph: require('../assets/book-icons/eph.webp'),
  phi: require('../assets/book-icons/php.webp'),
  col: require('../assets/book-icons/col.webp'),
  '1th': require('../assets/book-icons/1th.webp'),
  '2th': require('../assets/book-icons/2th.webp'),
  '1ti': require('../assets/book-icons/1ti.webp'),
  '2ti': require('../assets/book-icons/2ti.webp'),
  tit: require('../assets/book-icons/tit.webp'),
  phm: require('../assets/book-icons/phm.webp'),
  heb: require('../assets/book-icons/heb.webp'),
  jas: require('../assets/book-icons/jas.webp'),
  '1pe': require('../assets/book-icons/1pe.webp'),
  '2pe': require('../assets/book-icons/2pe.webp'),
  '1jn': require('../assets/book-icons/1jn.webp'),
  '2jn': require('../assets/book-icons/2jn.webp'),
  '3jn': require('../assets/book-icons/3jn.webp'),
  jud: require('../assets/book-icons/jud.webp'),
  rev: require('../assets/book-icons/rev.webp')
};
/* eslint-enable @typescript-eslint/no-require-imports, @typescript-eslint/no-unsafe-assignment */

// Build the BOOK_GRAPHICS map using the book IDs from bibleStructure.ts
export const BOOK_GRAPHICS: Record<string, ImageSourcePropType> =
  Object.fromEntries(
    BIBLE_BOOKS.map((book) => [book.id, BOOK_ICON_MAP[book.id]]).filter(
      (entry): entry is [string, ImageSourcePropType] => entry[1] !== undefined
    )
  );

// Simple emoji mapping for performance (used when USE_SVG_ICONS = false)
export const BOOK_EMOJIS: Record<string, string> = {
  // Old Testament
  gen: '🌱',
  exo: '🚶',
  lev: '⚖️',
  num: '🔢',
  deu: '📜',
  jos: '⚔️',
  jdg: '👨‍⚖️',
  rut: '🌾',
  '1sa': '👑',
  '2sa': '🏰',
  '1ki': '👑',
  '2ki': '🏰',
  '1ch': '📚',
  '2ch': '📖',
  ezr: '🏗️',
  neh: '🧱',
  est: '👸',
  job: '😢',
  psa: '🎵',
  pro: '💡',
  ecc: '🤔',
  sng: '💕',
  isa: '👁️',
  jer: '😭',
  lam: '💧',
  ezk: '🔥',
  dan: '🦁',
  hos: '💔',
  joe: '🦗',
  amo: '🏔️',
  oba: '⚡',
  jon: '🐋',
  mic: '⚖️',
  nah: '🌪️',
  hab: '❓',
  zep: '🔥',
  hag: '🏗️',
  zec: '👁️',
  mal: '💰',

  // New Testament
  mat: '👨',
  mar: '🦁',
  luk: '🐂',
  joh: '🦅',
  act: '🔥',
  rom: '🏛️',
  '1co': '💕',
  '2co': '🪖',
  gal: '🗽',
  eph: '⚔️',
  phi: '😊',
  col: '👑',
  '1th': '🎺',
  '2th': '⏰',
  '1ti': '👨‍💼',
  '2ti': '📝',
  tit: '🏗️',
  phm: '🤝',
  heb: '🎪',
  jas: '⚖️',
  '1pe': '🪨',
  '2pe': '🔥',
  '1jn': '📝',
  '2jn': '✉️',
  '3jn': '✍️',
  jud: '⚡',
  rev: '👁️'
};
