// Book emojis mapping
export const BOOK_EMOJIS: Record<string, string> = {
  // Old Testament
  gen: '🌱',
  exo: '🚶‍♂️',
  lev: '⚖️',
  num: '🔢',
  deu: '📜',
  jos: '⚔️',
  jdg: '👨‍⚖️',
  rut: '🌾',
  '1sa': '👑',
  '2sa': '🏰',
  '1ki': '👑',
  '2ki': '🏰',
  '1ch': '📚',
  '2ch': '📖',
  ezr: '🏗️',
  neh: '🧱',
  est: '👸',
  job: '😢',
  psa: '🎵',
  pro: '💡',
  ecc: '🤔',
  sng: '💕',
  isa: '👁️',
  jer: '😭',
  lam: '💧',
  ezk: '🔥',
  dan: '🦁',
  hos: '💔',
  joe: '🦗',
  amo: '🏔️',
  oba: '⚡',
  jon: '🐋',
  mic: '⚖️',
  nah: '🌪️',
  hab: '❓',
  zep: '🔥',
  hag: '🏗️',
  zec: '👁️',
  mal: '💰',

  // New Testament
  mat: '👨', // Man/Angel for Matthew
  mar: '🦁', // Lion for Mark
  luk: '🐂', // Ox/Bull for Luke
  joh: '🦅', // Eagle for John
  act: '🔥',
  rom: '🏛️',
  '1co': '💕',
  '2co': '🪖', // Paul's absence/travel
  gal: '🗽',
  eph: '⚔️',
  php: '😊',
  col: '👑',
  '1th': '🎺',
  '2th': '⏰',
  '1ti': '👨‍💼',
  '2ti': '📝',
  tit: '🏗️',
  phm: '🤝',
  heb: '🎪',
  jas: '⚖️',
  '1pe': '🪨',
  '2pe': '🔥',
  '1jo': '📝',
  '2jo': '✉️',
  '3jo': '✍️',
  jud: '⚡',
  rev: '👁️'
};
