# See https://docs.powersync.com/self-hosting/telemetry
telemetry:
  # Opt out of reporting anonymized usage metrics to PowerSync telemetry service
  disable_telemetry_sharing: true

# Settings for source database replication
replication:
  connections:
    - type: postgresql
      uri: !env PS_DATA_SOURCE_URI

      # SSL settings
      sslmode: 'verify-full' # Temporarily changed from 'verify-full' for troubleshooting

# Connection settings for sync bucket storage
storage:
  type: mongodb
  uri: mongodb://mongo:27017/powersync_demo

# The port which the PowerSync API server will listen on
port: !env PS_PORT

# Specify sync rules
sync_rules:
  path: sync-rules.yml

# Client (application end user) authentication settings
client_auth:
  supabase: true
  supabase_jwt_secret: !env PS_SUPABASE_JWT_SECRET

api:
  tokens:
    # These tokens are used for local admin API route authentication
    - use_a_better_token_in_production
