name: Create development builds

on:
  push:
    branches: ['dev']

jobs:
  android_development_build:
    name: Build Android (Development)
    type: build
    params:
      platform: android
      profile: development
  # ios_device_development_build:
  #   name: Build iOS device
  #   type: build
  #   params:
  #     platform: ios
  #     profile: development
  # ios_simulator_development_build:
  #   name: Build iOS simulator
  #   type: build
  #   params:
  #     platform: ios
  #     profile: development-simulator
