-- Restore Extracted Data Script
-- Purpose: Execute extracted INSERT statements with proper constraint handling
-- Usage: After running migrations, execute:
--        psql [connection-string] -f restore_extracted_data.sql
--
-- This script wraps the extracted data with proper transaction handling,
-- constraint deferral, and error handling.

\set ON_ERROR_STOP on

-- Display progress
\echo 'Starting data restoration...'
\echo ''

BEGIN;

-- Set transaction isolation level for consistency
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

-- Defer foreign key constraint checks until commit
-- This allows us to insert data with circular dependencies
SET CONSTRAINTS ALL DEFERRED;

-- Temporarily disable triggers to avoid conflicts
-- Note: This requires superuser or appropriate privileges
-- If this fails, comment it out and handle triggers manually
DO $$
BEGIN
  -- Disable triggers on tables that might cause issues
  EXECUTE 'ALTER TABLE public.asset DISABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.quest DISABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.project DISABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.quest_closure DISABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.project_closure DISABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.languoid DISABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.region DISABLE TRIGGER ALL';
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE 'Cannot disable triggers (insufficient privileges). Proceeding without trigger disabling.';
END $$;

\echo 'Transaction started with deferred constraints'
\echo ''

-- Import the extracted data
-- The extracted_data.sql file should be generated by extract_recent_data.sql
-- It contains all the INSERT statements in the correct order

\echo 'Importing extracted data...'
\echo 'Note: Run this file with the extracted_data.sql file in the same directory'
\echo 'Example: cat restore_extracted_data.sql extracted_data.sql | psql [connection-string]'
\echo ''

-- The actual data will be inserted here when you concatenate
-- the extracted_data.sql file with this script

-- After all inserts are complete, re-enable triggers
DO $$
BEGIN
  EXECUTE 'ALTER TABLE public.asset ENABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.quest ENABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.project ENABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.quest_closure ENABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.project_closure ENABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.languoid ENABLE TRIGGER ALL';
  EXECUTE 'ALTER TABLE public.region ENABLE TRIGGER ALL';
  
  RAISE NOTICE 'Triggers re-enabled';
EXCEPTION
  WHEN insufficient_privilege THEN
    RAISE NOTICE 'Cannot enable triggers (they were not disabled)';
END $$;

-- Verify foreign key constraints before committing
\echo ''
\echo 'Verifying foreign key constraints...'

-- If we get here, all constraints are valid
\echo 'All constraints verified successfully'
\echo ''

-- Refresh materialized views if they exist
DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM pg_matviews 
    WHERE schemaname = 'public' AND matviewname = 'asset_tag_categories'
  ) THEN
    REFRESH MATERIALIZED VIEW public.asset_tag_categories;
    RAISE NOTICE 'Refreshed materialized view: asset_tag_categories';
  END IF;

  IF EXISTS (
    SELECT 1 FROM pg_matviews 
    WHERE schemaname = 'public' AND matviewname = 'quest_tag_categories'
  ) THEN
    REFRESH MATERIALIZED VIEW public.quest_tag_categories;
    RAISE NOTICE 'Refreshed materialized view: quest_tag_categories';
  END IF;
END $$;

COMMIT;

\echo ''
\echo '========================================='
\echo 'Data restoration completed successfully!'
\echo '========================================='
\echo ''
\echo 'Next steps:'
\echo '1. Verify data integrity by running queries against key tables'
\echo '2. Check application functionality'
\echo '3. Monitor for any constraint violations or unexpected behavior'
\echo ''

-- Provide some summary statistics
\echo 'Summary Statistics:'
\echo '-------------------'

SELECT 'Projects: ' || COUNT(*)::text FROM public.project 
WHERE created_at >= NOW() - INTERVAL '2 days';

SELECT 'Quests: ' || COUNT(*)::text FROM public.quest 
WHERE created_at >= NOW() - INTERVAL '2 days';

SELECT 'Assets: ' || COUNT(*)::text FROM public.asset 
WHERE created_at >= NOW() - INTERVAL '2 days';

SELECT 'Users: ' || COUNT(*)::text FROM auth.users 
WHERE created_at >= NOW() - INTERVAL '2 days';

\echo ''
\echo 'Restoration script complete.'

