name: preview
on: pull_request

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: ${{ github.ref != 'refs/heads/main' }}

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup
        uses: ./tooling/github/setup-expo
        with:
          EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto --platform android
